services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '${PORT}:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-app-network

  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - nest-app-network

networks:
  nest-app-network:

volumes:
  mysql_data:
  node_modules: